python TWTrigger_Maker.py -y 16 -d W
python TWTrigger_Maker.py -y 17 -d W
python TWTrigger_Maker.py -y 18 -d W
python TWTrigger_Maker.py -y 16 -d tW
python TWTrigger_Maker.py -y 17 -d tW
python TWTrigger_Maker.py -y 18 -d tW
python TWTrigger_Maker.py -y 16 -d t
python TWTrigger_Maker.py -y 17 -d t
python TWTrigger_Maker.py -y 18 -d t
python TWTrigger_Maker.py -y 16 -d tt
python TWTrigger_Maker.py -y 17 -d tt
python TWTrigger_Maker.py -y 18 -d tt
