eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_1-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_2-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_3-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_4-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_5-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_6-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_7-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_8-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_9-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_10-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_11-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_12-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_13-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_14-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_15-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_16-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_17-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_18-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_19-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_20-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_21-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_22-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_23-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_24-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_25-26.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataD_26-26.root
