eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_1-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_2-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_3-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_4-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_5-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_6-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_7-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_8-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_9-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_10-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_11-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_12-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_13-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_14-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_15-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_16-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_17-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_18-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_19-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_20-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_21-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_22-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_23-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_24-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_25-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_26-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_27-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_28-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_29-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_30-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_31-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_32-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_33-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_34-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_35-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_36-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_37-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_38-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_39-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_40-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_41-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_42-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_43-44.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_t_44-44.root
