eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_1-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_2-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_3-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_4-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_5-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_6-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_7-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_8-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_9-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_10-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_11-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_12-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_13-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_14-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_15-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_16-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_17-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_18-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_19-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_20-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_21-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_22-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_23-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_24-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_25-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_26-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_27-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_28-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_29-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_30-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_31-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_32-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_33-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_34-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_35-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_36-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_37-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_38-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_39-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_40-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_41-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_42-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_43-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_44-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_45-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_46-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_47-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_48-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_49-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_50-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_51-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_52-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_53-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_54-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_55-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_56-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_57-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_58-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_59-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_60-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_61-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_62-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_63-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_64-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_65-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_66-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_67-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_68-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_69-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_70-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_71-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_72-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_73-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_74-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_75-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_76-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_77-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_78-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_79-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_80-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_81-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_82-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_83-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_84-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_85-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_86-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_87-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_88-89.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataG_89-89.root
