eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_1-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_2-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_3-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_4-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_5-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_6-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_7-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_8-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_9-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_10-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_11-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_12-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_13-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_14-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_15-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_16-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_17-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_18-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_19-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_20-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_21-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_22-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_23-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_24-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_25-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_26-27.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_singletop_tB_27-27.root
