eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_1-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_2-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_3-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_4-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_5-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_6-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_7-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_8-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_9-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_10-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_11-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_12-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_13-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_14-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_15-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_16-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_17-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_18-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_19-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_20-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_21-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_22-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_23-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_24-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_25-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_26-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_27-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_28-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_29-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_30-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_31-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_32-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_33-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_34-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_35-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_36-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_37-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_38-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_39-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_40-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_41-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_42-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_43-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_44-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_45-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_46-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_47-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_48-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_49-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_50-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_51-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_52-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_53-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_54-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_55-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_56-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_57-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_58-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_59-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_60-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_61-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_62-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_63-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_64-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_65-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_66-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_67-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_68-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_69-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_70-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_71-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_72-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_73-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_74-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_75-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_76-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_77-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_78-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_79-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_80-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_81-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_82-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_83-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_84-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_85-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_86-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_87-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_88-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_89-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_90-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_91-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_92-93.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataB_93-93.root
