eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_1-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_2-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_3-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_4-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_5-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_6-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_7-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_8-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_9-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_10-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_11-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_12-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_13-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_14-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_15-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_16-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_17-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_18-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_19-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_20-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_21-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_22-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_23-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_24-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_25-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_26-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_27-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_28-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_29-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_30-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_31-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_32-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_33-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_34-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_35-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_36-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_37-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_38-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_39-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_40-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_41-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_42-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_43-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_44-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_45-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_46-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_47-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_48-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_49-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_50-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_51-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_52-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_53-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_54-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_55-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_56-57.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataC_57-57.root
