eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_1-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_2-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_3-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_4-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_5-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_6-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_7-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_8-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_9-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_10-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_11-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_12-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_13-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_14-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_15-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_16-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_17-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_18-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_19-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_20-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_21-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_22-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_23-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_24-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_25-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_26-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_27-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_28-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_29-30.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_30-30.root
