eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_1-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_2-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_3-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_4-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_5-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_6-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_7-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_8-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_9-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_10-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_11-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_12-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_13-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_14-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_15-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_16-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_17-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_18-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_19-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_20-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_21-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_22-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_23-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_24-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_25-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_26-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_27-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_28-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_29-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_30-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_31-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_32-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_33-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_34-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_35-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_36-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_37-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_38-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_39-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_40-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_41-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_42-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_43-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_44-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_45-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_46-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_47-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_48-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_49-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_50-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_51-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_52-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_53-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_54-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_55-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_56-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_57-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_58-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_59-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_60-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_61-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_62-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_63-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_64-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_65-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_66-67.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataF_67-67.root
