eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_1-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_2-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_3-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_4-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_5-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_6-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_7-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_8-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_9-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_10-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_11-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_12-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_13-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_14-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_15-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_16-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_17-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_18-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_19-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_20-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_21-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_22-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_23-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_24-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_25-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_26-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_27-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_28-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_29-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_30-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataF_31-31.root
