eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_1-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_2-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_3-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_4-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_5-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_6-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_7-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_8-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_9-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_10-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_11-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_12-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_13-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_14-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_15-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_16-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_17-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_18-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_19-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_20-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_21-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_22-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_23-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_24-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_25-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_26-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_27-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_28-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_29-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_30-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_31-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_32-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_33-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_34-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_35-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_36-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_37-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_38-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_39-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_40-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_41-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_42-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_43-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_44-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_45-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_46-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_47-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_48-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_49-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_50-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_51-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_52-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_53-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_54-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_55-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_56-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_57-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_58-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_59-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_60-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_61-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_62-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_63-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_64-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_65-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_66-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_67-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_68-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_69-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_70-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_71-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_dataC_72-72.root
