eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_1-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_2-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_3-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_4-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_5-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_6-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_7-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_8-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_9-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_10-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_11-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_12-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_13-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_14-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_15-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_16-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_17-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_18-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_19-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_20-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_21-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_22-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_23-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_24-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_25-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_26-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_27-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_28-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_29-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_30-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_31-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_32-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_33-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_34-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_35-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_36-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_37-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_38-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_39-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_40-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_41-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_42-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_43-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_44-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_45-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_46-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_47-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_48-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_49-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_50-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_51-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_52-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_53-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_54-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_55-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_56-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_57-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_58-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_59-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_60-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_61-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_62-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_63-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_64-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_65-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_66-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_67-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_68-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_69-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_70-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_71-72.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_ttbar_72-72.root
