eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_1-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_2-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_3-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_4-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_5-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_6-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_7-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_8-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_9-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_10-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_11-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_12-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_13-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_14-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_15-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_16-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_17-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_18-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_19-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_20-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_21-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_22-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_23-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_24-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_25-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_26-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_27-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_28-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_29-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_30-31.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataC_31-31.root
