eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_1-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_2-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_3-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_4-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_5-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_6-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_7-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_8-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_9-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_10-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_11-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_12-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_13-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_14-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_15-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_16-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_17-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_18-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_19-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_20-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_21-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_22-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_23-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_24-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_25-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_26-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_27-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_28-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_29-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_30-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_31-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_32-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_33-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_34-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_35-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_36-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_37-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_38-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_39-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_40-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_41-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_42-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_43-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_44-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_45-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_46-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_47-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_48-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_49-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_50-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_51-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_52-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_53-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_54-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_55-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_56-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_57-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_58-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_59-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_60-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_61-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_62-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_63-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_64-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_65-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_66-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_67-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_68-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_69-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_70-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_71-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_72-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_73-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_74-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_75-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_76-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_77-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_78-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_79-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_80-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_81-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_82-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_83-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_84-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_85-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_86-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_87-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_88-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_89-90.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_singletop_tB_90-90.root
