eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_1-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_2-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_3-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_4-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_5-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_6-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_7-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_8-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_9-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_10-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_11-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_12-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_13-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_14-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_15-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_16-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_17-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_18-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_19-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_20-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_21-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_22-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_23-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_24-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_25-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_26-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_27-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_28-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_29-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_30-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_31-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_32-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_33-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_34-35.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_ttbar_semilep_35-35.root
