eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_1-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_2-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_3-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_4-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_5-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_6-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_7-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_8-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_9-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_10-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_11-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_12-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_13-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_14-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_15-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_16-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_17-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_18-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_19-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_20-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_21-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_22-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_23-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_24-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_25-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_26-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_27-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_28-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_29-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_30-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_31-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_32-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_33-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_34-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_35-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_36-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_37-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_38-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_39-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_40-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_41-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_42-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_43-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_44-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_45-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_46-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_47-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_48-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_49-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_50-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_51-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_52-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_53-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_54-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_55-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_56-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_57-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_58-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_59-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_60-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_61-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_62-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_63-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_64-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_65-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_66-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_67-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_68-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_69-70.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees18_ttbar_semilep_70-70.root
