eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_1-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_2-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_3-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_4-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_5-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_6-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_7-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_8-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_9-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_10-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_11-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_12-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_13-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_14-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_15-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_16-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_17-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_18-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_19-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_20-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_21-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_22-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_23-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_24-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_25-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_26-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_27-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_28-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_29-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_30-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_31-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_32-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_33-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_34-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_35-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_36-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_37-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_38-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_39-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_40-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_41-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_42-43.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataD_43-43.root
