eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_1-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_2-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_3-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_4-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_5-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_6-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_7-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_8-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_9-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_10-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_11-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_12-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_13-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_14-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_15-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_16-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_17-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_18-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_19-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_20-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_21-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_22-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_23-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_24-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_25-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_26-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_27-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_28-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_29-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_30-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_31-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_32-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_33-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_34-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_35-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_36-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_37-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_38-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_39-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_40-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_41-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_42-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_43-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_44-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_45-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_46-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_47-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_48-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_49-50.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees16_dataE_50-50.root
