eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_1-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_2-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_3-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_4-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_5-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_6-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_7-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_8-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_9-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_10-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_11-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_12-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_13-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_14-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_15-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_16-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_17-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_18-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_19-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_20-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_21-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_22-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_23-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_24-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_25-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_26-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_27-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_28-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_29-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_30-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_31-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_32-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_33-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_34-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_35-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_36-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_37-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_38-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_39-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_40-41.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataB_41-41.root
