eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_1-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_2-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_3-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_4-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_5-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_6-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_7-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_8-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_9-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_10-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_11-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_12-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_13-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_14-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_15-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_16-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_17-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_18-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_19-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_20-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_21-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_22-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_23-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_24-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_25-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_26-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_27-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_28-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_29-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_30-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_31-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_32-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_33-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_34-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_35-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_36-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_37-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_38-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_39-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_40-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_41-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_42-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_43-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_44-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_45-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_46-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_47-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_48-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_49-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_50-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_51-52.root
eosrm /store/user/lcorcodi/bstar_nano/bstarTrees17_dataE_52-52.root
